name: CMake on a single platform

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pcap
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev

    - name: clean
      run: ./build.sh clean

    - name: debug build
      run: ./build.sh debug

    - name: release build
      run: ./build.sh release

    - name: clean
      run: ./build.sh clean

    - name: debug build with pcap disabled
      run: CMAKE_OPTS="-D USE_PCAP=OFF" ./build.sh debug

    - name: release build with pcap disabled
      run: CMAKE_OPTS="-D USE_PCAP=OFF" ./build.sh release
