name: Unit Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pcap
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev nmap

    - name: clean
      run: ./build.sh clean

    - name: debug build with tests enabled
      run: CMAKE_OPTS="-D BUILD_TESTS=ON" ./build.sh debug

    - name: release build with tests enabled
      run: CMAKE_OPTS="-D BUILD_TESTS=ON" ./build.sh release

    - name: run unit tests
      run: ctest --test-dir debug && ctest --test-dir release